" ~/.vimrc - Vim configuration (offline, no plugins)

" --- General ---
set nocompatible
set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8
filetype plugin indent on
syntax enable

" --- Display ---
set number
set relativenumber
set cursorline
set showmatch
set showcmd
set showmode
set laststatus=2
set ruler
set wildmenu
set wildmode=longest:full,full
set scrolloff=8
set sidescrolloff=8
set signcolumn=yes
set title
set colorcolumn=80,120

" --- Search ---
set hlsearch
set incsearch
set ignorecase
set smartcase
nnoremap <Esc><Esc> :nohlsearch<CR>

" --- Indentation ---
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set shiftround

" --- Behavior ---
set hidden
set backspace=indent,eol,start
set clipboard=unnamedplus
set mouse=a
set splitbelow
set splitright
set autoread
set confirm
set noswapfile
set nobackup
set nowritebackup

" --- Undo persistence ---
set undofile
set undodir=~/.vim/undodir
if !isdirectory(&undodir)
    call mkdir(&undodir, 'p', 0700)
endif

" --- History ---
set history=1000

" --- Ctags ---
set tags=./tags;,tags;

" --- Statusline ---
set statusline=
set statusline+=%#PmenuSel#
set statusline+=\ %f
set statusline+=\ %m%r
set statusline+=%=
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\ [%{&fileformat}]
set statusline+=\ %l:%c
set statusline+=\ %p%%
set statusline+=\

" --- Window navigation ---
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" --- Buffer navigation ---
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>

" --- Leader key ---
let mapleader = " "
let maplocalleader = " "

" --- Leader mappings ---
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>e :Explore<CR>
nnoremap <leader>b :ls<CR>:b<Space>

" --- netrw (file explorer) ---
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

" --- Trim trailing whitespace on save ---
autocmd BufWritePre * %s/\s\+$//e

" --- File type specific ---
autocmd FileType yaml setlocal ts=2 sw=2 sts=2
autocmd FileType json setlocal ts=2 sw=2 sts=2
autocmd FileType javascript setlocal ts=2 sw=2 sts=2
autocmd FileType typescript setlocal ts=2 sw=2 sts=2
autocmd FileType html setlocal ts=2 sw=2 sts=2
autocmd FileType css setlocal ts=2 sw=2 sts=2
autocmd FileType ruby setlocal ts=2 sw=2 sts=2
autocmd FileType lua setlocal ts=2 sw=2 sts=2
autocmd FileType make setlocal noexpandtab
